# Generated by Django 4.2 on 2023-04-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('nombre', models.CharField(max_length=70)),
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='directorio_candidato')),
                ('certificado_antecedentes', models.FileField(blank=True, null=True, upload_to='directorio_candidato/')),
                ('hoja_de_vida_conductor', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('certificado_residencia', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('certificado_afiliacion_afp', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('certificado_afiliacion_salud', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('fotocopia_cedula_identidad', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('fotocopia_licencia_conducir', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('curriculum_vitae', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('ultimo_finiquito', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('documentacion_que_acredite_el_cargo', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('certificado_estudios', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('certificado_titulo', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('credencial_resolucion_sns_sernageomin', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('examen_preocupacional_salud', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('examen_preocupacional_alcohol_drogas', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('examen_psicosensometrico', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('certificado_sustancias_peligrosas', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('certificacion_rigger', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('certificacion_pluma', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('certificacion_choferes_operadores', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('situacion_militar', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('declaracion_jurada_salud', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('odi_collahuasi_covid19', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('reglamento_interno_excon', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('ficha_bhp_emex', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('odis_tortolas', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('reglamento_conduccion_recibo_tortolas', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('reglamento_condiccion_tortolas_anexo1', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('solicitud_evaluacion_conduccion_tortolas', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('odis_conduccion_qb2', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('registro_asistencia_induccion_qb2', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('solicitud_licencia_interna_qb2', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('toma_conocimiento_covid19', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
                ('odis_qb22', models.FileField(blank=True, null=True, upload_to='directorio_candidato')),
            ],
            options={
                'verbose_name': 'candidato',
                'verbose_name_plural': 'candidatos',
            },
        ),
    ]
