# Generated by Django 4.2 on 2023-04-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0002_candidato_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='estado',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
