# Generated by Django 4.2 on 2023-04-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0003_candidato_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='certificado_antecedentes',
            field=models.FileField(blank=True, null=True, upload_to='directorio_candidato'),
        ),
    ]
