# Generated by Django 4.2 on 2023-04-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0005_alter_candidato_certificacion_choferes_operadores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='estado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
