# Generated by Django 4.2 on 2023-04-24 16:52

import candidato.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0006_alter_candidato_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='certificacion_choferes_operadores',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='certificacion_pluma',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='certificacion_rigger',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='certificado_afiliacion_afp',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='certificado_afiliacion_salud',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='certificado_antecedentes',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='certificado_estudios',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='certificado_residencia',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='certificado_sustancias_peligrosas',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='certificado_titulo',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='credencial_resolucion_sns_sernageomin',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='curriculum_vitae',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='declaracion_jurada_salud',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='documentacion_que_acredite_el_cargo',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='examen_preocupacional_alcohol_drogas',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='examen_preocupacional_salud',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='examen_psicosensometrico',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='ficha_bhp_emex',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='fotocopia_cedula_identidad',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='fotocopia_licencia_conducir',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='hoja_de_vida_conductor',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='odi_collahuasi_covid19',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='odis_conduccion_qb2',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='odis_qb22',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='odis_tortolas',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='registro_asistencia_induccion_qb2',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='reglamento_condiccion_tortolas_anexo1',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='reglamento_conduccion_recibo_tortolas',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='reglamento_interno_excon',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='situacion_militar',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='solicitud_evaluacion_conduccion_tortolas',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='solicitud_licencia_interna_qb2',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='toma_conocimiento_covid19',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='ultimo_finiquito',
            field=models.FileField(blank=True, null=True, upload_to=candidato.models.upload_directory_name),
        ),
    ]
