# Generated by Django 4.2 on 2023-05-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0008_candidato_centro_de_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='centro_de_costo',
            field=models.CharField(blank=True, choices=[('1', 'Quebrada Blanca'), ('2', 'Lo Pinto'), ('3', 'Oficina Central'), ('4', 'Carbonato'), ('5', 'Toconao'), ('6', 'Centinela'), ('7', 'Spence'), ('8', 'La Negra')], max_length=30, null=True),
        ),
    ]
