# Generated by Django 4.2 on 2023-05-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0009_alter_candidato_centro_de_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='nombre',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
